package org.atlasapi.feeds.xmltv;

import java.util.Map;

import com.google.common.collect.ImmutableMap;

public class XmlTvFeedGenreMap {

    private static final Map<String, String> genreMap = ImmutableMap.<String, String>builder()
            .put("1000","Drama")
            .put("1F00","Drama")
            .put("1F01","Drama")
            .put("1F05","Drama")
            .put("1F06","Childrens")
            .put("1F07","Drama")
            .put("1F08","Drama")
            .put("1F09","Drama")
            .put("1100","Drama")
            .put("1F0A","Drama")
            .put("1F0B","Drama")
            .put("1F0C","Drama")
            .put("1F0D","Drama")
            .put("1F0E","Drama")
            .put("1F04","Drama")
            .put("1200","Drama")
            .put("1F0F","Drama")
            .put("1F10","Drama")
            .put("1F11","Drama")
            .put("1300","Drama")
            .put("1F02","Drama")
            .put("1F03","Drama")
            .put("1400","Comedy")
            .put("1F12","Sitcom")
            .put("1F13","Comedy")
            .put("1F14","Comedy")
            .put("1500","Soap")
            .put("1600","Drama")
            .put("1F15","Drama")
            .put("1700","Drama")
            .put("1F17","Drama")
            .put("1F16","Drama")
            .put("1800","Drama")
            .put("2000","News")
            .put("2F02","News")
            .put("2F03","News")
            .put("2F04","News")
            .put("2F05","News")
            .put("2F06","News")
            .put("2200","Current affairs")
            .put("2300","Documentary")
            .put("2F07","Current affairs")
            .put("2F08","Current affairs")
            .put("3000","Entertainment")
            .put("3F00","Entertainment")
            .put("3F01","Entertainment")
            .put("3F02","Entertainment")
            .put("3100","Entertainment")
            .put("3F03","Entertainment")
            .put("3200","Entertainment")
            .put("3300","Entertainment")
            .put("4000","Sport")
            .put("4100","Sport")
            .put("4200","Sport")
            .put("4300","Sport")
            .put("4400","Sport")
            .put("4500","Sport")
            .put("4600","Sport")
            .put("4700","Sport")
            .put("4800","Sport")
            .put("4900","Sport")
            .put("4A00","Sport")
            .put("4B00","Sport")
            .put("4C00","Sport")
            .put("4F00","Sport")
            .put("4F01","Sport")
            .put("4F02","Sport")
            .put("4F03","Sport")
            .put("4F04","Sport")
            .put("4F05","Sport")
            .put("4F06","Sport")
            .put("4F07","Sport")
            .put("4F08","Sport")
            .put("4F09","Sport")
            .put("4F0A","Sport")
            .put("4F0B","Sport")
            .put("4F0C","Sport")
            .put("4F0D","Sport")
            .put("4F0E","Sport")
            .put("4F0F","Sport")
            .put("4F10","Sport")
            .put("4F11","Sport")
            .put("4F12","Sport")
            .put("4F13","Sport")
            .put("4F14","Sport")
            .put("4F15","Sport")
            .put("4F16","Sport")
            .put("4F17","Sport")
            .put("4F19","Sport")
            .put("4F1A","Sport")
            .put("4F1B","Sport")
            .put("4F1C","Sport")
            .put("4F1D","Sport")
            .put("4F1E","Sport")
            .put("4F1F","Sport")
            .put("4F20","Sport")
            .put("4F21","Sport")
            .put("4F22","Sport")
            .put("4F23","Sport")
            .put("4F24","Sport")
            .put("4F25","Sport")
            .put("4F26","Sport")
            .put("4F27","Sport")
            .put("4F28","Sport")
            .put("4F29","Sport")
            .put("4F2A","Sport")
            .put("4F2B","Sport")
            .put("4F2C","Sport")
            .put("4F2D","Sport")
            .put("4F2E","Sport")
            .put("4F2F","Sport")
            .put("4F30","Sport")
            .put("4F31","Sport")
            .put("4F32","Sport")
            .put("4F33","Sport")
            .put("4F34","Sport")
            .put("4F35","Sport")
            .put("4F36","Sport")
            .put("4F37","Sport")
            .put("4F39","Sport")
            .put("4F3A","Sport")
            .put("4F3B","Sport")
            .put("4F3C","Sport")
            .put("4F3D","Sport")
            .put("4F3E","Sport")
            .put("4F3F","Sport")
            .put("4F40","Sport")
            .put("4F41","Sport")
            .put("4F42","Sport")
            .put("4F43","Sport")
            .put("4F44","Sport")
            .put("4F45","Sport")
            .put("4F46","Sport")
            .put("4F47","Sport")
            .put("4F48","Sport")
            .put("4F49","Sport")
            .put("4F4A","Sport")
            .put("5000","Childrens")
                    .put("5100","Childrens")
                    .put("5200","Childrens")
                    .put("5300","Childrens")
                    .put("5400","Childrens")
                    .put("5500","Childrens")
                            .put("6000","Music")
                    .put("6F01","Music")
                    .put("6F02","Music")
                    .put("6F03","Music")
                    .put("6F06","Music")
                    .put("6F07","Music")
                    .put("6F08","Music")
                    .put("6200","Music")
                    .put("6300","Music")
                    .put("6400","Music")
                    .put("6F09","Music")
                    .put("6F0A","Music")
                    .put("6600","Arts")
                    .put("6F05","Arts")
                            .put("7000","Arts")
                    .put("7100","Arts")
                    .put("7200","Arts")
                    .put("7400","Arts")
                    .put("7500","Arts")
                    .put("7600","Arts")
                    .put("7700","Arts")
                    .put("7800","Arts")
                    .put("7900","Arts")
                    .put("7A00","Arts")
                    .put("7B00","Arts")
                    .put("8000","Current affairs")
                    .put("8200","Current affairs")
                            
                    .put("9000", "Reality")
                    .put("9F02","Reality")
                    .put("9F03","Lifestyle")
                    .put("9F04","History")
                    .put("9F05","History")
                    .put("9F06","History")
                    .put("9100","Nature")
                    .put("9F07","Nature")
                    .put("9F08","Science")
                    .put("9F09","Nature")
                    .put("9F0A","Nature")
                    .put("9200","Science")
                    .put("9300","Science")
                    .put("9400","Lifestyle")
                    .put("9500","Lifestyle")
                    .put("9F00","Education")
                    .put("9700","Education")
                    .put("A000","Lifestyle")
                    .put("AF01","Lifestyle")
                    .put("AF02","Lifestyle")
                    .put("A100","Lifestyle")
                    .put("A200","Lifestyle")
                    .put("A300","Lifestyle")
                    .put("A400","Lifestyle")
                    .put("A500","Food")
                    .put("A600","Lifestyle")
                    .put("A700","Lifestyle")
                    .put("AF00","Lifestyle")
                    .put("AF03","Property")
                    .put("B300","Live")
                    .put("BF00","Off-Air")
                    .put("BF01","Film").build();
    
    public XmlTvFeedGenreMap() {
    }
    
    static final String genreUriPrefix = "http://pressassociation.com/genres/";
    
    public String mapGenreUri(String genreUri) {
        return genreMap.get(genreUri.substring(genreUriPrefix.length()));
    }

}
