//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata._2010;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import tva.metadata.extended._2010.ExtendedContentDescriptionType;
import tva.mpeg7._2008.ExtendedLanguageType;
import tva.mpeg7._2008.TitleType;


/**
 * <p>Java class for BasicContentDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BasicContentDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{urn:tva:mpeg7:2008}TitleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ShortTitle" type="{urn:tva:metadata:2010}ShortTitleType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Synopsis" type="{urn:tva:metadata:2010}SynopsisType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Keyword" type="{urn:tva:metadata:2010}KeywordType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Genre" type="{urn:tva:metadata:2010}GenreType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ParentalGuidance" type="{urn:tva:metadata:2010}TVAParentalGuidanceType" minOccurs="0"/>
 *         &lt;element name="Language" type="{urn:tva:mpeg7:2008}ExtendedLanguageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CreditsList" type="{urn:tva:metadata:2010}CreditsListType" minOccurs="0"/>
 *         &lt;element name="RelatedMaterial" type="{urn:tva:metadata:2010}RelatedMaterialType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProductionDate" type="{urn:tva:metadata:2010}TVATimeType" minOccurs="0"/>
 *         &lt;element name="ProductionLocation" type="{urn:tva:mpeg7:2008}regionCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="PurchaseList" type="{urn:tva:metadata:2010}PurchaseListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BasicContentDescriptionType", propOrder = {
    "title",
    "shortTitle",
    "synopsis",
    "keyword",
    "genre",
    "parentalGuidance",
    "language",
    "creditsList",
    "relatedMaterial",
    "productionDate",
    "productionLocation",
    "duration",
    "purchaseList"
})
@XmlSeeAlso({
    ExtendedContentDescriptionType.class
})
public class BasicContentDescriptionType {

    @XmlElement(name = "Title")
    protected List<TitleType> title;
    @XmlElement(name = "ShortTitle")
    protected List<ShortTitleType> shortTitle;
    @XmlElement(name = "Synopsis")
    protected List<SynopsisType> synopsis;
    @XmlElement(name = "Keyword")
    protected List<KeywordType> keyword;
    @XmlElement(name = "Genre")
    protected List<GenreType> genre;
    @XmlElement(name = "ParentalGuidance")
    protected TVAParentalGuidanceType parentalGuidance;
    @XmlElement(name = "Language")
    protected List<ExtendedLanguageType> language;
    @XmlElement(name = "CreditsList")
    protected CreditsListType creditsList;
    @XmlElement(name = "RelatedMaterial")
    protected List<RelatedMaterialType> relatedMaterial;
    @XmlElement(name = "ProductionDate")
    protected TVATimeType productionDate;
    @XmlElement(name = "ProductionLocation")
    protected List<String> productionLocation;
    @XmlElement(name = "Duration")
    protected Duration duration;
    @XmlElement(name = "PurchaseList")
    protected PurchaseListType purchaseList;

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleType }
     * 
     * 
     */
    public List<TitleType> getTitle() {
        if (title == null) {
            title = new ArrayList<TitleType>();
        }
        return this.title;
    }

    /**
     * Gets the value of the shortTitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shortTitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShortTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShortTitleType }
     * 
     * 
     */
    public List<ShortTitleType> getShortTitle() {
        if (shortTitle == null) {
            shortTitle = new ArrayList<ShortTitleType>();
        }
        return this.shortTitle;
    }

    /**
     * Gets the value of the synopsis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the synopsis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSynopsis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SynopsisType }
     * 
     * 
     */
    public List<SynopsisType> getSynopsis() {
        if (synopsis == null) {
            synopsis = new ArrayList<SynopsisType>();
        }
        return this.synopsis;
    }

    /**
     * Gets the value of the keyword property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyword().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeywordType }
     * 
     * 
     */
    public List<KeywordType> getKeyword() {
        if (keyword == null) {
            keyword = new ArrayList<KeywordType>();
        }
        return this.keyword;
    }

    /**
     * Gets the value of the genre property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genre property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenre().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GenreType }
     * 
     * 
     */
    public List<GenreType> getGenre() {
        if (genre == null) {
            genre = new ArrayList<GenreType>();
        }
        return this.genre;
    }

    /**
     * Gets the value of the parentalGuidance property.
     * 
     * @return
     *     possible object is
     *     {@link TVAParentalGuidanceType }
     *     
     */
    public TVAParentalGuidanceType getParentalGuidance() {
        return parentalGuidance;
    }

    /**
     * Sets the value of the parentalGuidance property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVAParentalGuidanceType }
     *     
     */
    public void setParentalGuidance(TVAParentalGuidanceType value) {
        this.parentalGuidance = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendedLanguageType }
     * 
     * 
     */
    public List<ExtendedLanguageType> getLanguage() {
        if (language == null) {
            language = new ArrayList<ExtendedLanguageType>();
        }
        return this.language;
    }

    /**
     * Gets the value of the creditsList property.
     * 
     * @return
     *     possible object is
     *     {@link CreditsListType }
     *     
     */
    public CreditsListType getCreditsList() {
        return creditsList;
    }

    /**
     * Sets the value of the creditsList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditsListType }
     *     
     */
    public void setCreditsList(CreditsListType value) {
        this.creditsList = value;
    }

    /**
     * Gets the value of the relatedMaterial property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedMaterial property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedMaterial().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedMaterialType }
     * 
     * 
     */
    public List<RelatedMaterialType> getRelatedMaterial() {
        if (relatedMaterial == null) {
            relatedMaterial = new ArrayList<RelatedMaterialType>();
        }
        return this.relatedMaterial;
    }

    /**
     * Gets the value of the productionDate property.
     * 
     * @return
     *     possible object is
     *     {@link TVATimeType }
     *     
     */
    public TVATimeType getProductionDate() {
        return productionDate;
    }

    /**
     * Sets the value of the productionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TVATimeType }
     *     
     */
    public void setProductionDate(TVATimeType value) {
        this.productionDate = value;
    }

    /**
     * Gets the value of the productionLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productionLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductionLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getProductionLocation() {
        if (productionLocation == null) {
            productionLocation = new ArrayList<String>();
        }
        return this.productionLocation;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the purchaseList property.
     * 
     * @return
     *     possible object is
     *     {@link PurchaseListType }
     *     
     */
    public PurchaseListType getPurchaseList() {
        return purchaseList;
    }

    /**
     * Sets the value of the purchaseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurchaseListType }
     *     
     */
    public void setPurchaseList(PurchaseListType value) {
        this.purchaseList = value;
    }

}
