//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata._2010;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CRIDRefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CRIDRefType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="crid" use="required" type="{urn:tva:metadata:2010}CRIDType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CRIDRefType")
@XmlSeeAlso({
    com.youview.refdata.schemas._2011_07_06.PackageMembershipType.Package.class,
    BaseMemberOfType.class
})
public class CRIDRefType {

    @XmlAttribute(required = true)
    protected String crid;

    /**
     * Gets the value of the crid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCrid() {
        return crid;
    }

    /**
     * Sets the value of the crid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCrid(String value) {
        this.crid = value;
    }

}
