//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata._2010;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import tva.mpeg7._2008.UniqueIDType;


/**
 * <p>Java class for GroupInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GroupInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GroupType" type="{urn:tva:metadata:2010}BaseProgramGroupTypeType"/>
 *         &lt;element name="BasicDescription" type="{urn:tva:metadata:2010}BasicContentDescriptionType"/>
 *         &lt;element name="MemberOf" type="{urn:tva:metadata:2010}BaseMemberOfType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OtherIdentifier" type="{urn:tva:mpeg7:2008}UniqueIDType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:tva:metadata:2010}fragmentIdentification"/>
 *       &lt;attribute name="groupId" use="required" type="{urn:tva:metadata:2010}CRIDType" />
 *       &lt;attribute name="ordered" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *       &lt;attribute name="serviceIDRef" type="{urn:tva:metadata:2010}TVAIDRefType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GroupInformationType", propOrder = {
    "groupType",
    "basicDescription",
    "memberOf",
    "otherIdentifier"
})
public class GroupInformationType {

    @XmlElement(name = "GroupType", required = true)
    protected BaseProgramGroupTypeType groupType;
    @XmlElement(name = "BasicDescription", required = true)
    protected BasicContentDescriptionType basicDescription;
    @XmlElement(name = "MemberOf")
    protected List<BaseMemberOfType> memberOf;
    @XmlElement(name = "OtherIdentifier")
    protected List<UniqueIDType> otherIdentifier;
    @XmlAttribute(required = true)
    protected String groupId;
    @XmlAttribute
    protected Boolean ordered;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute
    protected String serviceIDRef;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fragmentExpirationDate;

    /**
     * Gets the value of the groupType property.
     * 
     * @return
     *     possible object is
     *     {@link BaseProgramGroupTypeType }
     *     
     */
    public BaseProgramGroupTypeType getGroupType() {
        return groupType;
    }

    /**
     * Sets the value of the groupType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseProgramGroupTypeType }
     *     
     */
    public void setGroupType(BaseProgramGroupTypeType value) {
        this.groupType = value;
    }

    /**
     * Gets the value of the basicDescription property.
     * 
     * @return
     *     possible object is
     *     {@link BasicContentDescriptionType }
     *     
     */
    public BasicContentDescriptionType getBasicDescription() {
        return basicDescription;
    }

    /**
     * Sets the value of the basicDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicContentDescriptionType }
     *     
     */
    public void setBasicDescription(BasicContentDescriptionType value) {
        this.basicDescription = value;
    }

    /**
     * Gets the value of the memberOf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberOf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberOf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseMemberOfType }
     * 
     * 
     */
    public List<BaseMemberOfType> getMemberOf() {
        if (memberOf == null) {
            memberOf = new ArrayList<BaseMemberOfType>();
        }
        return this.memberOf;
    }

    /**
     * Gets the value of the otherIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueIDType }
     * 
     * 
     */
    public List<UniqueIDType> getOtherIdentifier() {
        if (otherIdentifier == null) {
            otherIdentifier = new ArrayList<UniqueIDType>();
        }
        return this.otherIdentifier;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupId(String value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the ordered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOrdered() {
        if (ordered == null) {
            return false;
        } else {
            return ordered;
        }
    }

    /**
     * Sets the value of the ordered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOrdered(Boolean value) {
        this.ordered = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the serviceIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceIDRef() {
        return serviceIDRef;
    }

    /**
     * Sets the value of the serviceIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceIDRef(String value) {
        this.serviceIDRef = value;
    }

    /**
     * Gets the value of the fragmentExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFragmentExpirationDate() {
        return fragmentExpirationDate;
    }

    /**
     * Sets the value of the fragmentExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFragmentExpirationDate(XMLGregorianCalendar value) {
        this.fragmentExpirationDate = value;
    }

}
