//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata._2010;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;
import com.youview.refdata.schemas._2011_07_06.ExtendedOnDemandProgramType;


/**
 * <p>Java class for OnDemandProgramType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OnDemandProgramType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:metadata:2010}ProgramLocationType">
 *       &lt;sequence>
 *         &lt;element name="PublishedDuration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *         &lt;element name="StartOfAvailability" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EndOfAvailability" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ImmediateViewing" type="{urn:tva:metadata:2010}FlagType" minOccurs="0"/>
 *         &lt;element name="Free" type="{urn:tva:metadata:2010}FlagType"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:tva:metadata:2010}fragmentIdentification"/>
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *       &lt;attribute name="serviceIDRef" use="required" type="{urn:tva:metadata:2010}TVAIDRefType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OnDemandProgramType", propOrder = {
    "publishedDuration",
    "startOfAvailability",
    "endOfAvailability",
    "immediateViewing",
    "free"
})
@XmlSeeAlso({
    ExtendedOnDemandProgramType.class
})
public class OnDemandProgramType
    extends ProgramLocationType
{

    @XmlElement(name = "PublishedDuration")
    protected Duration publishedDuration;
    @XmlElement(name = "StartOfAvailability")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startOfAvailability;
    @XmlElement(name = "EndOfAvailability")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endOfAvailability;
    @XmlElement(name = "ImmediateViewing")
    protected FlagType immediateViewing;
    @XmlElement(name = "Free", required = true)
    protected FlagType free;
    @XmlAttribute(namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;
    @XmlAttribute(required = true)
    protected String serviceIDRef;
    @XmlAttribute
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fragmentExpirationDate;

    /**
     * Gets the value of the publishedDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getPublishedDuration() {
        return publishedDuration;
    }

    /**
     * Sets the value of the publishedDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setPublishedDuration(Duration value) {
        this.publishedDuration = value;
    }

    /**
     * Gets the value of the startOfAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartOfAvailability() {
        return startOfAvailability;
    }

    /**
     * Sets the value of the startOfAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartOfAvailability(XMLGregorianCalendar value) {
        this.startOfAvailability = value;
    }

    /**
     * Gets the value of the endOfAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndOfAvailability() {
        return endOfAvailability;
    }

    /**
     * Sets the value of the endOfAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndOfAvailability(XMLGregorianCalendar value) {
        this.endOfAvailability = value;
    }

    /**
     * Gets the value of the immediateViewing property.
     * 
     * @return
     *     possible object is
     *     {@link FlagType }
     *     
     */
    public FlagType getImmediateViewing() {
        return immediateViewing;
    }

    /**
     * Sets the value of the immediateViewing property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagType }
     *     
     */
    public void setImmediateViewing(FlagType value) {
        this.immediateViewing = value;
    }

    /**
     * Gets the value of the free property.
     * 
     * @return
     *     possible object is
     *     {@link FlagType }
     *     
     */
    public FlagType getFree() {
        return free;
    }

    /**
     * Sets the value of the free property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlagType }
     *     
     */
    public void setFree(FlagType value) {
        this.free = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the serviceIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceIDRef() {
        return serviceIDRef;
    }

    /**
     * Sets the value of the serviceIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceIDRef(String value) {
        this.serviceIDRef = value;
    }

    /**
     * Gets the value of the fragmentExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFragmentExpirationDate() {
        return fragmentExpirationDate;
    }

    /**
     * Sets the value of the fragmentExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFragmentExpirationDate(XMLGregorianCalendar value) {
        this.fragmentExpirationDate = value;
    }

}
