//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata._2010;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PurchaseListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchaseListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="PurchaseItem" type="{urn:tva:metadata:2010}PurchaseItemType"/>
 *           &lt;element name="PurchaseIdRef" type="{urn:tva:metadata:2010}TVAIDRefType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchaseListType", propOrder = {
    "purchaseItemOrPurchaseIdRef"
})
public class PurchaseListType {

    @XmlElements({
        @XmlElement(name = "PurchaseItem", type = PurchaseItemType.class),
        @XmlElement(name = "PurchaseIdRef", type = String.class)
    })
    protected List<Object> purchaseItemOrPurchaseIdRef;

    /**
     * Gets the value of the purchaseItemOrPurchaseIdRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purchaseItemOrPurchaseIdRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurchaseItemOrPurchaseIdRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PurchaseItemType }
     * {@link String }
     * 
     * 
     */
    public List<Object> getPurchaseItemOrPurchaseIdRef() {
        if (purchaseItemOrPurchaseIdRef == null) {
            purchaseItemOrPurchaseIdRef = new ArrayList<Object>();
        }
        return this.purchaseItemOrPurchaseIdRef;
    }

}
