//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata._2010;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import tva.metadata.extended._2010.ExtendedRelatedMaterialType;
import tva.mpeg7._2008.MediaLocatorType;
import tva.mpeg7._2008.TextualType;
import tva.mpeg7._2008.TitleMediaType;


/**
 * <p>Java class for RelatedMaterialType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedMaterialType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HowRelated" type="{urn:tva:metadata:2010}ControlledTermType" minOccurs="0"/>
 *         &lt;element name="Format" type="{urn:tva:metadata:2010}ControlledTermType" minOccurs="0"/>
 *         &lt;element name="MediaLocator" type="{urn:tva:mpeg7:2008}MediaLocatorType"/>
 *         &lt;element name="PromotionalText" type="{urn:tva:mpeg7:2008}TextualType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PromotionalMedia" type="{urn:tva:mpeg7:2008}TitleMediaType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SourceMediaLocator" type="{urn:tva:mpeg7:2008}MediaLocatorType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedMaterialType", propOrder = {
    "howRelated",
    "format",
    "mediaLocator",
    "promotionalText",
    "promotionalMedia",
    "sourceMediaLocator"
})
@XmlSeeAlso({
    ExtendedRelatedMaterialType.class
})
public class RelatedMaterialType {

    @XmlElement(name = "HowRelated")
    protected ControlledTermType howRelated;
    @XmlElement(name = "Format")
    protected ControlledTermType format;
    @XmlElement(name = "MediaLocator", required = true)
    protected MediaLocatorType mediaLocator;
    @XmlElement(name = "PromotionalText")
    protected List<TextualType> promotionalText;
    @XmlElement(name = "PromotionalMedia")
    protected List<TitleMediaType> promotionalMedia;
    @XmlElement(name = "SourceMediaLocator")
    protected MediaLocatorType sourceMediaLocator;

    /**
     * Gets the value of the howRelated property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledTermType }
     *     
     */
    public ControlledTermType getHowRelated() {
        return howRelated;
    }

    /**
     * Sets the value of the howRelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledTermType }
     *     
     */
    public void setHowRelated(ControlledTermType value) {
        this.howRelated = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledTermType }
     *     
     */
    public ControlledTermType getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledTermType }
     *     
     */
    public void setFormat(ControlledTermType value) {
        this.format = value;
    }

    /**
     * Gets the value of the mediaLocator property.
     * 
     * @return
     *     possible object is
     *     {@link MediaLocatorType }
     *     
     */
    public MediaLocatorType getMediaLocator() {
        return mediaLocator;
    }

    /**
     * Sets the value of the mediaLocator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaLocatorType }
     *     
     */
    public void setMediaLocator(MediaLocatorType value) {
        this.mediaLocator = value;
    }

    /**
     * Gets the value of the promotionalText property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotionalText property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotionalText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextualType }
     * 
     * 
     */
    public List<TextualType> getPromotionalText() {
        if (promotionalText == null) {
            promotionalText = new ArrayList<TextualType>();
        }
        return this.promotionalText;
    }

    /**
     * Gets the value of the promotionalMedia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the promotionalMedia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPromotionalMedia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TitleMediaType }
     * 
     * 
     */
    public List<TitleMediaType> getPromotionalMedia() {
        if (promotionalMedia == null) {
            promotionalMedia = new ArrayList<TitleMediaType>();
        }
        return this.promotionalMedia;
    }

    /**
     * Gets the value of the sourceMediaLocator property.
     * 
     * @return
     *     possible object is
     *     {@link MediaLocatorType }
     *     
     */
    public MediaLocatorType getSourceMediaLocator() {
        return sourceMediaLocator;
    }

    /**
     * Sets the value of the sourceMediaLocator property.
     * 
     * @param value
     *     allowed object is
     *     {@link MediaLocatorType }
     *     
     */
    public void setSourceMediaLocator(MediaLocatorType value) {
        this.sourceMediaLocator = value;
    }

}
