//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata._2010;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import tva.mpeg7._2008.TextualType;


/**
 * <p>Java class for ServiceInformationNameType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceInformationNameType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:tva:mpeg7:2008>TextualType">
 *       &lt;attribute name="length" type="{urn:tva:metadata:2010}serviceInformationNameLengthType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceInformationNameType")
public class ServiceInformationNameType
    extends TextualType
{

    @XmlAttribute
    protected ServiceInformationNameLengthType length;

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceInformationNameLengthType }
     *     
     */
    public ServiceInformationNameLengthType getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceInformationNameLengthType }
     *     
     */
    public void setLength(ServiceInformationNameLengthType value) {
        this.length = value;
    }

}
