//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata._2010;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import tva.mpeg7._2008.MediaRelIncrTimePointType;


/**
 * <p>Java class for TVAMediaRelIncrTimePointType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TVAMediaRelIncrTimePointType">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;urn:tva:mpeg7:2008>MediaRelIncrTimePointType">
 *       &lt;attribute name="mediaTimeUnit" type="{urn:tva:mpeg7:2008}mediaDurationType" default="PT1N1000F" />
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TVAMediaRelIncrTimePointType")
public class TVAMediaRelIncrTimePointType
    extends MediaRelIncrTimePointType
{


}
