//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata.extended._2010;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import tva.metadata._2010.TVAMainType;


/**
 * <p>Java class for ExtendedTVAMainType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedTVAMainType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:metadata:2010}TVAMainType">
 *       &lt;sequence>
 *         &lt;element name="PackageTable" type="{urn:tva:metadata:extended:2010}PackageTableType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedTVAMainType", propOrder = {
    "packageTable"
})
public class ExtendedTVAMainType
    extends TVAMainType
{

    @XmlElement(name = "PackageTable")
    protected PackageTableType packageTable;

    /**
     * Gets the value of the packageTable property.
     * 
     * @return
     *     possible object is
     *     {@link PackageTableType }
     *     
     */
    public PackageTableType getPackageTable() {
        return packageTable;
    }

    /**
     * Sets the value of the packageTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackageTableType }
     *     
     */
    public void setPackageTable(PackageTableType value) {
        this.packageTable = value;
    }

}
