//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata.extended._2010;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tva.metadata.extended._2010 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tva.metadata.extended._2010
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ComponentType }
     * 
     */
    public ComponentType createComponentType() {
        return new ComponentType();
    }

    /**
     * Create an instance of {@link ExtendedContentDescriptionType.SourceLocation }
     * 
     */
    public ExtendedContentDescriptionType.SourceLocation createExtendedContentDescriptionTypeSourceLocation() {
        return new ExtendedContentDescriptionType.SourceLocation();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link VideoAttributesType }
     * 
     */
    public VideoAttributesType createVideoAttributesType() {
        return new VideoAttributesType();
    }

    /**
     * Create an instance of {@link TargetingInformationType }
     * 
     */
    public TargetingInformationType createTargetingInformationType() {
        return new TargetingInformationType();
    }

    /**
     * Create an instance of {@link ContentTargetType }
     * 
     */
    public ContentTargetType createContentTargetType() {
        return new ContentTargetType();
    }

    /**
     * Create an instance of {@link ExtendedRelatedMaterialType }
     * 
     */
    public ExtendedRelatedMaterialType createExtendedRelatedMaterialType() {
        return new ExtendedRelatedMaterialType();
    }

    /**
     * Create an instance of {@link ExtendedTVAMainType }
     * 
     */
    public ExtendedTVAMainType createExtendedTVAMainType() {
        return new ExtendedTVAMainType();
    }

    /**
     * Create an instance of {@link ConditionType }
     * 
     */
    public ConditionType createConditionType() {
        return new ConditionType();
    }

    /**
     * Create an instance of {@link ExtendedContentDescriptionType }
     * 
     */
    public ExtendedContentDescriptionType createExtendedContentDescriptionType() {
        return new ExtendedContentDescriptionType();
    }

    /**
     * Create an instance of {@link PackageType }
     * 
     */
    public PackageType createPackageType() {
        return new PackageType();
    }

    /**
     * Create an instance of {@link AudioAttributesType }
     * 
     */
    public AudioAttributesType createAudioAttributesType() {
        return new AudioAttributesType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link ObjectDescriptionType }
     * 
     */
    public ObjectDescriptionType createObjectDescriptionType() {
        return new ObjectDescriptionType();
    }

    /**
     * Create an instance of {@link ResourceTypeType }
     * 
     */
    public ResourceTypeType createResourceTypeType() {
        return new ResourceTypeType();
    }

    /**
     * Create an instance of {@link SelectionType }
     * 
     */
    public SelectionType createSelectionType() {
        return new SelectionType();
    }

    /**
     * Create an instance of {@link SpatialIntervalType }
     * 
     */
    public SpatialIntervalType createSpatialIntervalType() {
        return new SpatialIntervalType();
    }

    /**
     * Create an instance of {@link StillImageContentAttributesType }
     * 
     */
    public StillImageContentAttributesType createStillImageContentAttributesType() {
        return new StillImageContentAttributesType();
    }

    /**
     * Create an instance of {@link DescriptorType }
     * 
     */
    public DescriptorType createDescriptorType() {
        return new DescriptorType();
    }

    /**
     * Create an instance of {@link ContentPropertiesType }
     * 
     */
    public ContentPropertiesType createContentPropertiesType() {
        return new ContentPropertiesType();
    }

    /**
     * Create an instance of {@link ChoiceType }
     * 
     */
    public ChoiceType createChoiceType() {
        return new ChoiceType();
    }

    /**
     * Create an instance of {@link TemporalIntervalType }
     * 
     */
    public TemporalIntervalType createTemporalIntervalType() {
        return new TemporalIntervalType();
    }

    /**
     * Create an instance of {@link RelationType }
     * 
     */
    public RelationType createRelationType() {
        return new RelationType();
    }

    /**
     * Create an instance of {@link PackageTableType }
     * 
     */
    public PackageTableType createPackageTableType() {
        return new PackageTableType();
    }

}
