//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package tva.metadata.extended._2010;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpatialIntervalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpatialIntervalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="XSpatialInterval" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="YSpatialInterval" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="spatialIntervalUnit" type="{urn:tva:metadata:extended:2010}SpatialRelIntervalType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpatialIntervalType", propOrder = {
    "xSpatialInterval",
    "ySpatialInterval"
})
public class SpatialIntervalType {

    @XmlElement(name = "XSpatialInterval")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger xSpatialInterval;
    @XmlElement(name = "YSpatialInterval")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger ySpatialInterval;
    @XmlAttribute
    protected String spatialIntervalUnit;

    /**
     * Gets the value of the xSpatialInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXSpatialInterval() {
        return xSpatialInterval;
    }

    /**
     * Sets the value of the xSpatialInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXSpatialInterval(BigInteger value) {
        this.xSpatialInterval = value;
    }

    /**
     * Gets the value of the ySpatialInterval property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getYSpatialInterval() {
        return ySpatialInterval;
    }

    /**
     * Sets the value of the ySpatialInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setYSpatialInterval(BigInteger value) {
        this.ySpatialInterval = value;
    }

    /**
     * Gets the value of the spatialIntervalUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpatialIntervalUnit() {
        return spatialIntervalUnit;
    }

    /**
     * Sets the value of the spatialIntervalUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpatialIntervalUnit(String value) {
        this.spatialIntervalUnit = value;
    }

}
