//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package com.youview.refdata.schemas._2011_07_06;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import tva.metadata._2010.OnDemandProgramType;


/**
 * <p>Java class for ExtendedOnDemandProgramType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedOnDemandProgramType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:tva:metadata:2010}OnDemandProgramType">
 *       &lt;sequence>
 *         &lt;element name="ContentReferencingInformation" type="{http://refdata.youview.com/schemas/Metadata/2012-11-19}ContentReferencingInformationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedOnDemandProgramType", propOrder = {
    "contentReferencingInformation"
})
public class ExtendedOnDemandProgramType
    extends OnDemandProgramType
{

    @XmlElement(name = "ContentReferencingInformation")
    protected ContentReferencingInformationType contentReferencingInformation;

    /**
     * Gets the value of the contentReferencingInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ContentReferencingInformationType }
     *     
     */
    public ContentReferencingInformationType getContentReferencingInformation() {
        return contentReferencingInformation;
    }

    /**
     * Sets the value of the contentReferencingInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentReferencingInformationType }
     *     
     */
    public void setContentReferencingInformation(ContentReferencingInformationType value) {
        this.contentReferencingInformation = value;
    }

}
