//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.10 at 02:33:06 PM BST 
//


package com.youview.refdata.schemas._2011_07_06;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import tva.metadata._2010.AVAttributesType;
import tva.metadata._2010.FlagType;
import tva.metadata._2010.ServiceInformationType;
import tva.metadata._2010.TVAParentalGuidanceType;
import tva.metadata.extended._2010.TargetingInformationType;
import tva.mpeg7._2008.UniqueIDType;

/**
 * <p>Java class for ExtendedServiceInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedServiceInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{urn:tva:metadata:2010}ServiceInformationType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ParentalGuidance" type="{urn:tva:metadata:2010}TVAParentalGuidanceType" minOccurs="0"/&gt;
 *         &lt;element name="AVAttributes" type="{urn:tva:metadata:2010}AVAttributesType" minOccurs="0"/&gt;
 *         &lt;element name="Free" type="{urn:tva:metadata:2010}FlagType" minOccurs="0"/&gt;
 *         &lt;element name="OtherIdentifier" type="{urn:tva:mpeg7:2008}UniqueIDType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TargetingInformation" type="{urn:tva:metadata:extended:2010}TargetingInformationType" minOccurs="0"/&gt;
 *         &lt;element name="ContentReferencingInformation" type="{http://refdata.youview.com/schemas/Metadata/2012-11-19}ContentReferencingInformationType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedServiceInformationType", propOrder = {
    "parentalGuidance",
    "avAttributes",
    "free",
    "otherIdentifier",
    "targetingInformation",
    "contentReferencingInformation"
})
public class ExtendedServiceInformationType
    extends ServiceInformationType
{

    @XmlElement(name = "ParentalGuidance")
    protected TVAParentalGuidanceType parentalGuidance;
    @XmlElement(name = "AVAttributes")
    protected AVAttributesType avAttributes;
    @XmlElement(name = "Free")
    protected FlagType free;
    @XmlElement(name = "OtherIdentifier")
    protected List<UniqueIDType> otherIdentifier;
    @XmlElement(name = "TargetingInformation")
    protected TargetingInformationType targetingInformation;
    @XmlElement(name = "ContentReferencingInformation")
    protected ContentReferencingInformationType contentReferencingInformation;

    /**
     * Gets the value of the parentalGuidance property.
     *
     * @return
     *     possible object is
     *     {@link TVAParentalGuidanceType }
     *
     */
    public TVAParentalGuidanceType getParentalGuidance() {
        return parentalGuidance;
    }

    /**
     * Sets the value of the parentalGuidance property.
     *
     * @param value
     *     allowed object is
     *     {@link TVAParentalGuidanceType }
     *
     */
    public void setParentalGuidance(TVAParentalGuidanceType value) {
        this.parentalGuidance = value;
    }

    /**
     * Gets the value of the avAttributes property.
     *
     * @return
     *     possible object is
     *     {@link AVAttributesType }
     *
     */
    public AVAttributesType getAVAttributes() {
        return avAttributes;
    }

    /**
     * Sets the value of the avAttributes property.
     *
     * @param value
     *     allowed object is
     *     {@link AVAttributesType }
     *
     */
    public void setAVAttributes(AVAttributesType value) {
        this.avAttributes = value;
    }

    /**
     * Gets the value of the free property.
     *
     * @return
     *     possible object is
     *     {@link FlagType }
     *
     */
    public FlagType getFree() {
        return free;
    }

    /**
     * Sets the value of the free property.
     *
     * @param value
     *     allowed object is
     *     {@link FlagType }
     *
     */
    public void setFree(FlagType value) {
        this.free = value;
    }

    /**
     * Gets the value of the otherIdentifier property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherIdentifier property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherIdentifier().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UniqueIDType }
     *
     *
     */
    public List<UniqueIDType> getOtherIdentifier() {
        if (otherIdentifier == null) {
            otherIdentifier = new ArrayList<UniqueIDType>();
        }
        return this.otherIdentifier;
    }

    /**
     * Gets the value of the targetingInformation property.
     *
     * @return
     *     possible object is
     *     {@link TargetingInformationType }
     *
     */
    public TargetingInformationType getTargetingInformation() {
        return targetingInformation;
    }

    /**
     * Sets the value of the targetingInformation property.
     *
     * @param value
     *     allowed object is
     *     {@link TargetingInformationType }
     *
     */
    public void setTargetingInformation(TargetingInformationType value) {
        this.targetingInformation = value;
    }

    /**
     * Gets the value of the contentReferencingInformation property.
     *
     * @return
     *     possible object is
     *     {@link ContentReferencingInformationType }
     *
     */
    public ContentReferencingInformationType getContentReferencingInformation() {
        return contentReferencingInformation;
    }

    /**
     * Sets the value of the contentReferencingInformation property.
     *
     * @param value
     *     allowed object is
     *     {@link ContentReferencingInformationType }
     *
     */
    public void setContentReferencingInformation(ContentReferencingInformationType value) {
        this.contentReferencingInformation = value;
    }

}
