//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//


package com.youview.refdata.schemas._2011_07_06;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.youview.refdata.schemas._2011_07_06 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.youview.refdata.schemas._2011_07_06
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExtendedOnDemandProgramType }
     * 
     */
    public ExtendedOnDemandProgramType createExtendedOnDemandProgramType() {
        return new ExtendedOnDemandProgramType();
    }

    /**
     * Create an instance of {@link PackageMembershipType.Package }
     * 
     */
    public PackageMembershipType.Package createPackageMembershipTypePackage() {
        return new PackageMembershipType.Package();
    }

    /**
     * Create an instance of {@link ContentReferencingInformationType }
     * 
     */
    public ContentReferencingInformationType createContentReferencingInformationType() {
        return new ContentReferencingInformationType();
    }

    /**
     * Create an instance of {@link ExtendedInstanceDescriptionType }
     * 
     */
    public ExtendedInstanceDescriptionType createExtendedInstanceDescriptionType() {
        return new ExtendedInstanceDescriptionType();
    }

    /**
     * Create an instance of {@link ExtendedPackageType }
     * 
     */
    public ExtendedPackageType createExtendedPackageType() {
        return new ExtendedPackageType();
    }

    /**
     * Create an instance of {@link ProgramGroupTypeType }
     * 
     */
    public ProgramGroupTypeType createProgramGroupTypeType() {
        return new ProgramGroupTypeType();
    }

    /**
     * Create an instance of {@link LocatorType }
     * 
     */
    public LocatorType createLocatorType() {
        return new LocatorType();
    }

    /**
     * Create an instance of {@link TargetPlaceType }
     * 
     */
    public TargetPlaceType createTargetPlaceType() {
        return new TargetPlaceType();
    }

    /**
     * Create an instance of {@link ExtendedPackageTableType }
     * 
     */
    public ExtendedPackageTableType createExtendedPackageTableType() {
        return new ExtendedPackageTableType();
    }

    /**
     * Create an instance of {@link ExtendedTargetingInformationType }
     * 
     */
    public ExtendedTargetingInformationType createExtendedTargetingInformationType() {
        return new ExtendedTargetingInformationType();
    }

    /**
     * Create an instance of {@link ServiceEndpointType }
     * 
     */
    public ServiceEndpointType createServiceEndpointType() {
        return new ServiceEndpointType();
    }

    /**
     * Create an instance of {@link PackageMembershipType }
     * 
     */
    public PackageMembershipType createPackageMembershipType() {
        return new PackageMembershipType();
    }

    /**
     * Create an instance of {@link ExtendedObjectDescriptionType }
     * 
     */
    public ExtendedObjectDescriptionType createExtendedObjectDescriptionType() {
        return new ExtendedObjectDescriptionType();
    }

    /**
     * Create an instance of {@link ExtendedServiceInformationType }
     * 
     */
    public ExtendedServiceInformationType createExtendedServiceInformationType() {
        return new ExtendedServiceInformationType();
    }

}
