//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.25 at 10:09:26 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://refdata.youview.com/schemas/Metadata/2012-11-19", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.youview.refdata.schemas._2011_07_06;
