//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 10:17:38 AM GMT 
//


package com.youview.refdata.schemas.youviewstatusreport._2010_12_07;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.youview.refdata.schemas.youviewstatusreport._2010_12_07 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.youview.refdata.schemas.youviewstatusreport._2010_12_07
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StatusReport }
     * 
     */
    public StatusReport createStatusReport() {
        return new StatusReport();
    }

    /**
     * Create an instance of {@link TransactionReportType }
     * 
     */
    public TransactionReportType createTransactionReportType() {
        return new TransactionReportType();
    }

    /**
     * Create an instance of {@link FragmentReportType }
     * 
     */
    public FragmentReportType createFragmentReportType() {
        return new FragmentReportType();
    }

    /**
     * Create an instance of {@link ControlledMessageType }
     * 
     */
    public ControlledMessageType createControlledMessageType() {
        return new ControlledMessageType();
    }

}
