//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 10:17:38 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://refdata.youview.com/schemas/YouViewStatusReport/2010-12-07", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.youview.refdata.schemas.youviewstatusreport._2010_12_07;
