//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.30 at 10:17:38 AM GMT 
//


package com.youview.refdata.schemas.youviewstatusreport._2010_12_07;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * A report on a metadata transaction
 * 
 * <p>Java class for TransactionReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionReportType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://refdata.youview.com/schemas/YouViewStatusReport/2010-12-07}ReportType">
 *       &lt;choice>
 *         &lt;element name="FragmentUpdateReport" type="{http://refdata.youview.com/schemas/YouViewStatusReport/2010-12-07}FragmentReportType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FragmentDeleteReport" type="{http://refdata.youview.com/schemas/YouViewStatusReport/2010-12-07}FragmentReportType" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="state" use="required" type="{http://refdata.youview.com/schemas/YouViewStatusReport/2010-12-07}TransactionStateType" />
 *       &lt;attribute name="transactionId" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionReportType", propOrder = {
    "fragmentUpdateReport",
    "fragmentDeleteReport"
})
public class TransactionReportType
    extends ReportType
{

    @XmlElement(name = "FragmentUpdateReport")
    protected List<FragmentReportType> fragmentUpdateReport;
    @XmlElement(name = "FragmentDeleteReport")
    protected FragmentReportType fragmentDeleteReport;
    @XmlAttribute(name = "state", required = true)
    protected TransactionStateType state;
    @XmlAttribute(name = "transactionId", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String transactionId;

    /**
     * Gets the value of the fragmentUpdateReport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fragmentUpdateReport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFragmentUpdateReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FragmentReportType }
     * 
     * 
     */
    public List<FragmentReportType> getFragmentUpdateReport() {
        if (fragmentUpdateReport == null) {
            fragmentUpdateReport = new ArrayList<FragmentReportType>();
        }
        return this.fragmentUpdateReport;
    }

    /**
     * Gets the value of the fragmentDeleteReport property.
     * 
     * @return
     *     possible object is
     *     {@link FragmentReportType }
     *     
     */
    public FragmentReportType getFragmentDeleteReport() {
        return fragmentDeleteReport;
    }

    /**
     * Sets the value of the fragmentDeleteReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link FragmentReportType }
     *     
     */
    public void setFragmentDeleteReport(FragmentReportType value) {
        this.fragmentDeleteReport = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionStateType }
     *     
     */
    public TransactionStateType getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionStateType }
     *     
     */
    public void setState(TransactionStateType value) {
        this.state = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

}
